name: Run Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules and test🔧
        run: yarn && yarn test
